version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
          timezone: Asia/Tokyo
      ignore:
          - dependency-name: 'playwright'
            versions: ['*']
          - dependency-name: '@playwright/test'
            versions: ['*']

      groups:
          dependencies:
              dependency-type: production
          devDependencies:
              dependency-type: development
