services:
    playwright:
        image: mcr.microsoft.com/playwright:v1.52.0
        ports:
            - 3010:3000
        entrypoint: npx playwright@1.52.0 run-server --port 3000
        extra_hosts:
            - 'host.docker.internal:host-gateway'
