packages:
    - 'apps/*'
    - 'packages/*'
    - 'configs/*'

catalogs:
    next14:
        'next': '14.2.22'
        '@next/bundle-analyzer': '14.2.22'

    next15:
        'next': '15.1.7'
        '@next/bundle-analyzer': '15.1.7'

    react18:
        'react': '18.3.1'
        'react-dom': '18.3.1'
        '@types/react': '18.3.1'
        '@types/react-dom': '18.3.1'

    react19:
        'react': '19.0.0'
        'react-dom': '19.0.0'
        '@types/react': '19.0.0'
        '@types/react-dom': '19.0.0'
