packages:
    - 'apps/*'
    - 'packages/*'
    - 'configs/*'

catalogs:
    next:
        'next': '14.2.22'
        '@next/bundle-analyzer': '14.2.22'

    react:
        'react': '18.3.1'
        'react-dom': '18.3.1'
        '@types/react': '18.3.1'
        '@types/react-dom': '18.3.1'
