packages:
    - 'apps/*'
    - 'packages/*'
    - 'configs/*'

catalogs:
    next14:
        'next': '^14.2.22'
        '@next/bundle-analyzer': '^14.2.22'

    react18:
        'react': ^18.3.1
        'react-dom': ^18.3.1
        '@types/react': ^18.3.1
        '@types/react-dom': ^18.3.1
