packages:
    - 'apps/*'
    - 'packages/*'
    - 'configs/*'

catalogs:
    react18:
        'react': ^18.3.1
        'react-dom': ^18.3.1
        '@types/react': ^18.3.1
        '@types/react-dom': ^18.3.1
