packages:
    - 'apps/*'
    - 'packages/*'
    - 'configs/*'

catalogs:
    next:
        'next': '15.3.2'
        '@next/bundle-analyzer': '15.3.2'

    react:
        'react': '19.1.0'
        'react-dom': '19.1.0'
        '@types/react': '19.1.0'
        '@types/react-dom': '19.1.0'
