import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import '@repo/ui/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Turborepo',
    description: 'Generated by create turbo',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}): JSX.Element {
    return (
        <html lang="ja">
            <body className={inter.className}>{children}</body>
        </html>
    )
}
